c1 = complex(input("digite um complexo [ex: 1+1j]: "))
c2 = complex(input("digite outro complexo [ex: 1-3j]: "))
c3 = complex(input("digite mais um complexo [ex: 3-2j]: "))

print("comutatividade")
print("soma")
print(f"c1+c2 = {c1+c2}")
print(f"c2+c1 = {c2+c1}")
print("produto")
print(f"c1*c2 = {c1*c2}")
print(f"c2*c1 = {c2*c1}")
print('\n')
print("associatividade")
print("soma")
print(f"(c1+c2)+c3 = {(c1+c2)+c3}")
print(f"c1+(x2+x3) = {c1+(c2+c3)}")
print("produto")
print(f"c1*(c2*c3) = {c1*(c2*c3)}")
print(f"(c1*c2)*c3 = {(c1*c2)*c3}")
print('\n')
print("distributividade")
print(f"c1*(c2+c3) = {c1*(c2+c3)}")
print(f"(c1*c2)+(c1*c3) = {(c1*c2)+(c1*c3)}")
